repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.6
  hooks:
  - id: ruff
    args:
    - --fix
    - --exit-non-zero-on-fix
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.1
  hooks:
  - id: mypy
    additional_dependencies:
    - types-colorama
    - types-python-dateutil
    - types-flask-cors
    - types-jsonschema
    - types-pillow
    - types-psycopg2
    - types-pyyaml
    - types-requests
    - types-tabulate
    - types-tqdm
