model:
  backbone: "convnextv2_tiny.fcmae"
  hidden_units: 0
  num_classes: 2
  freeze_backbone: true

data:
  root_dir: "dataset/train"
  nb_folds: 5
  batch_size: 32
  augmentation: false
  # as training data is imbalanced, we can use weighted sampler
  weighted_sampler: false
  test_dir: "dataset/test_images"

training:
  learning_rate: 1e-3
  lr_monitor: "train_loss"
  weight_decay: 1e-3
  nb_epochs: 40
  lr_decay_patience: 2
  lr_decay_threshold: 0.01
