model:
  backbone: "convnextv2_tiny.fcmae"
  hidden_units: 0
  num_classes: 2
  freeze_backbone: true

data:
  root_dir: "dataset/train"
  nb_folds: 3
  batch_size: 32

  # seed for splitting k-fold
  split_seed: 42
  augmentation: true

  # as training data is imbalanced, we can use weighted sampler
  weighted_sampler: true

  test_dir: "dataset/test_images"

training:
  learning_rate: 1e-3
  weight_decay: 1e-3
  nb_epochs: 50
  warmup_epochs: 5
  lr_decay_patience: 2
  lr_decay_threshold: 0.01
